### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by Seqway** [Seqway/ioBroker.opnsense_OLD#7]
2022-09-27:
- [ ] switch code to TypeScript
- [ ] pending

2022-09-25:
- [ ] #8
- [x] create objects testweise
- [x] apikey.json manually test
- [x] merge master and dev branch
